import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Island3(props) {
  const { nodes, materials } = useGLTF("/static/Island3.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.022}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={materials["terrain_atlas.terrain.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_1.geometry}
          material={materials["terrain_atlas.terrain_alpha"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_2.geometry}
          material={materials["terrain_atlas.terrain"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_3.geometry}
          material={materials["terrain_atlas.terrain_alpha.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_4.geometry}
          material={materials["terrain_atlas.terrain.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_5.geometry}
          material={materials["terrain_atlas.terrain.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_6.geometry}
          material={materials["terrain_atlas.terrain_alpha.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_7.geometry}
          material={materials["terrain_atlas.terrain_alpha.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_8.geometry}
          material={materials["terrain_atlas.terrain.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_9.geometry}
          material={materials.entity}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_10.geometry}
          material={materials.ui_text_font_default8_blend}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_11.geometry}
          material={materials["terrain_atlas.terrain_alpha.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_12.geometry}
          material={materials["terrain_atlas.terrain.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_13.geometry}
          material={materials["terrain_atlas.terrain_blend"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_14.geometry}
          material={materials["ui_text_font_default8_blend.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_15.geometry}
          material={materials["terrain_atlas.terrain_alpha.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_16.geometry}
          material={materials["terrain_atlas.terrain.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_17.geometry}
          material={materials["terrain_atlas.terrain_blend.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_18.geometry}
          material={materials["ui_text_font_default8_blend.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_19.geometry}
          material={materials["terrain_atlas.terrain_alpha.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_20.geometry}
          material={materials["terrain_atlas.terrain.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_21.geometry}
          material={materials["ui_text_font_default8_blend.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_22.geometry}
          material={materials["terrain_atlas.terrain_alpha.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_23.geometry}
          material={materials["terrain_atlas.terrain.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_24.geometry}
          material={materials["terrain_atlas.terrain_blend.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_25.geometry}
          material={materials["ui_text_font_default8_blend.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_26.geometry}
          material={materials["terrain_atlas.terrain_alpha.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_27.geometry}
          material={materials["terrain_atlas.terrain.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_28.geometry}
          material={materials["ui_text_font_default8_blend.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_29.geometry}
          material={materials["terrain_atlas.terrain.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_30.geometry}
          material={materials["terrain_atlas.terrain_alpha.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_31.geometry}
          material={materials["terrain_atlas.terrain_alpha.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_32.geometry}
          material={materials["terrain_atlas.terrain.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_33.geometry}
          material={materials["terrain_atlas.terrain_alpha.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_34.geometry}
          material={materials["terrain_atlas.terrain.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_35.geometry}
          material={materials["terrain_atlas.terrain_alpha.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_36.geometry}
          material={materials["terrain_atlas.terrain.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_37.geometry}
          material={materials["terrain_atlas.terrain_alpha.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_38.geometry}
          material={materials["terrain_atlas.terrain.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_39.geometry}
          material={materials["ui_text_font_default8_blend.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_40.geometry}
          material={materials["terrain_atlas.terrain_alpha.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_41.geometry}
          material={materials["terrain_atlas.terrain_blend.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_42.geometry}
          material={materials["terrain_atlas.terrain.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_43.geometry}
          material={materials["terrain_atlas.terrain_alpha.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_44.geometry}
          material={materials["terrain_atlas.terrain.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_45.geometry}
          material={materials["terrain_atlas.terrain.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_46.geometry}
          material={materials["terrain_atlas.terrain_alpha.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_47.geometry}
          material={materials["terrain_atlas.terrain_alpha.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_48.geometry}
          material={materials["terrain_atlas.terrain.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_49.geometry}
          material={materials["terrain_atlas.terrain.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_50.geometry}
          material={materials["terrain_atlas.terrain_alpha.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_51.geometry}
          material={materials["terrain_atlas.terrain_blend.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_52.geometry}
          material={materials["terrain_atlas.terrain.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_53.geometry}
          material={materials["terrain_atlas.terrain_alpha.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_54.geometry}
          material={materials["terrain_atlas.terrain.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_55.geometry}
          material={materials["terrain_atlas.terrain_alpha.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_56.geometry}
          material={materials["terrain_atlas.terrain.025"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_57.geometry}
          material={materials["terrain_atlas.terrain_alpha.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_58.geometry}
          material={materials["terrain_atlas.terrain_blend.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_59.geometry}
          material={materials["terrain_atlas.terrain_alpha.025"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_60.geometry}
          material={materials["terrain_atlas.terrain.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_61.geometry}
          material={materials["terrain_atlas.terrain.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_62.geometry}
          material={materials["terrain_atlas.terrain_alpha.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_63.geometry}
          material={materials["ui_text_font_default8_blend.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_64.geometry}
          material={materials["terrain_atlas.terrain_alpha.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_65.geometry}
          material={materials["terrain_atlas.terrain.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_66.geometry}
          material={materials["terrain_atlas.terrain_blend.007"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/static/Island3.glb");